### ISSUE TITLE
How can we configure .importjs.js which is documented in https://github.com/Galooshi/import-js?

### ISSUE THREAD

**Issue by xumc** [Galooshi/sublime-import-js#17]
Do we support other configuration items which are documented in https://github.com/Galooshi/import-js? for example, aliases, excludes and sortImports. I can only see there is "path" configuration in the package setting.

**Comment by trotzig** [comment]
Import-js can be configured for a project by dropping an `.importjs.js` file in the root of the project (where the package.json file exists). Here's the full list of configuration options: https://github.com/Galooshi/import-js#configuration

**Comment by monovertex** [comment]
@trotzig, I think this issue can be closed, right?

**Comment by trotzig** [comment]
Yep, correct!
