### ISSUE TITLE
Importjs for Angular5

### ISSUE THREAD

**Issue by ohabash** [Galooshi/sublime-import-js#18]
How do I use import js? The readme doesnt say what it even does or how to use it or what to expect.

But Im really curious if I can get it to help with importing modules quickly. Especially for Angular projects (typescript)

**Comment by trotzig** [comment]
Sorry that the readme doesn't have enough information. You should get a better sense by reading the readme for import-js, the underlying tool used by sublime-import-js: https://github.com/Galooshi/import-js

**Comment by trotzig** [comment]
I added a link at the top of the README to better guide people new to import-js: https://github.com/Galooshi/sublime-import-js/commit/fd57b28253135ba7aebc4a503234419c00a2e437

**Comment by ohabash** [comment]
ah this is great. thank you
