### ISSUE TITLE
Code of conduct link is invalid in CONTRIBUTING.md

### ISSUE THREAD

**Issue by monovertex** [Galooshi/sublime-import-js#20]
I plan on opening a PR to fix #1 and #19, but I'm not sure if there any special rules or guidelines to follow when writing the code.

Unfortunately the link to the code of conduct (http://todogroup.org/opencodeofconduct/#Import-JS/henric.trotzig@gmail.com) seems to be dead.

**Comment by trotzig** [comment]
That would be great! Just make sure you explain your changes well and keep them isolated (either different PRs or different commits) and you’re good to go. Bear in mind that some of the code in here is written by people without much python experience (e.g. me!) so if you see room for improvement, don’t hesitate to make the change!

**Comment by monovertex** [comment]
@trotzig, I opened a Pull Request to address this issue, add a linter and fix several linting issues. Please take a look at it when you have the time. Thanks!
