### ISSUE TITLE
Doesn't work with importjs@3.1.0

### ISSUE THREAD

**Issue by janpaul123** [Galooshi/sublime-import-js#23]
Keeps hanging on "Running ImportJS command…". Downgrading to 3.0.0 fixed the issue (and upgrading again reproduces the behaviour.)

**Comment by monovertex** [comment]
Is this a larger project? On the project I tested the update on (pretty large Ember codebase) it takes a while to start the daemon.

Can you run the importjs command from the CLI on the exact file you ran the command on and let me know what happens?

**Comment by trotzig** [comment]
Hi @janpaul123! Is it possible you're seeing this bug: https://github.com/Galooshi/import-js/issues/515 ?

**Comment by trotzig** [comment]
This should now be fixed. Try installing 3.1.1 (the latest import-js version) and see if that fixes things.
