### ISSUE TITLE
Not importing prop-types

### ISSUE THREAD

**Issue by darknblack** [Galooshi/sublime-import-js#24]
I am using React JS and the plugin can't import prop-types.

**Comment by trotzig** [comment]
Hi @darknblack! Can you tell me a little bit more on how you are importing:
- What's the name of the variable you use to reference prop-types? 
- Is "prop-types" listed in your `dependencies` section in package.json? Is it in `devDependencies`?

**Comment by darknblack** [comment]
* PropTypes
* It is in devDependencies.

**Comment by trotzig** [comment]
I see. You’ll have to either move it to `dependencies` or turn on the `importDevDependencies` configuration option for import-js: https://github.com/Galooshi/import-js/blob/master/README.md#importdevdependencies

**Comment by darknblack** [comment]
Thank you, it works now.
