### ISSUE TITLE
add import statement in top of a html file

### ISSUE THREAD

**Issue by iahu** [Galooshi/sublime-import-js#27]
Hi, call import command in a html file will add an import statement in the top of the file. It looks like that:
```html
import { renderStatus } from './helper';

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <script>
    renderStatus
  </script>
</body>
</html>
```

but, except it will in the script tag of the scope:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <script>
    import { renderStatus } from './helper';
    
    renderStatus
  </script>
</body>
</html>
```

Thanks you great work.

**Comment by trotzig** [comment]
Hi @iahu! Unfortunately, import-js only works well in javascript files. Supporting the scenario you outlined above is outside of the scope of this library.

**Comment by iahu** [comment]
Emm,  and it not work on vue.js sfc, as the same time. regret it.
