### ISSUE TITLE
Running ImportJS command... Commands no longer working

### ISSUE THREAD

**Issue by gla23** [Galooshi/sublime-import-js#28]
Thanks for this package. I've been using it for a while and it's been working fine, however today it's stopped working. When I run any of the import commands it says "Running ImportJS command..." in the bar at the bottom and doesn't do anything.

Just wondering whether you have come across this before?

I've tried reinstalling the package, going through the importjs setup again, and restarting sublime but it still does the same thing.
Thanks

**Comment by beinginorbit** [comment]
Same here, updating import-js seemed to help.

**Comment by gla23** [comment]
I moved over to VS code in the end.
