### ISSUE TITLE
Mysterious line-break inserted

### ISSUE THREAD

**Issue by trotzig** [Galooshi/sublime-import-js#3]
We have a file in our repo which, on running `ImportJS: Fix all imports` will insert a line-break in the middle of the file, seemingly random. The weird thing is that when running the `importjs` command in isolation on the command-line, the line-break isn't inserted. I've tried the same file in vim and it works the way expect it to work.

Here's an example `git diff` after importing with the Sublime plugin:

```
diff --git a/app/assets/components/pages/DistrictPage/index.jsx b/app/assets/components/pages/DistrictPage/index.jsx
index d832504..b752c66 100644
--- a/app/assets/components/pages/DistrictPage/index.jsx
+++ b/app/assets/components/pages/DistrictPage/index.jsx
@@ -1,5 +1,5 @@
-const { some } = require('underscore');
 const $ = require('jquery');
+const { some } = require('underscore');
 const DocumentTitle = require('react-document-title');
 const React = require('react');

@@ -527,7 +527,8 @@ const DistrictPage = React.createClass({
       currentProfile,
       district,
     } = this.props;
-    const canSeeVoterVerification = currentProfile.voter_verification &&
+    const canSeeVoterVerification = currentProfile.voter_verification 
+&&
       currentProfile.voter_verification.can_see_activity;

     return (
```

Notice the added line-break after `const canSeeVoterVerification = currentProfile.voter_verification`.

It should be noted that this file is quite large - over 1000 lines.

**Comment by lencioni** [comment]
It would be really helpful if you could put together a minimal repro case.

**Comment by trotzig** [comment]
Yeah, not sure how I'll do that right now. I can share some things I've found so far. First of all, the line-break is in the string before we pass it to the `import_js_replace` command. It might be "created" by json parsing somehow, because printing `result.get('fileContent')` will have the extra line-break.

**Comment by trotzig** [comment]
It's not "created" by json parsing. It's there when we convert the stdout stream to a string. One theory has been that it's related to buffer sizes. But changing `bufsize` has no effect.

https://docs.python.org/2/library/subprocess.html

**Comment by trotzig** [comment]
It's weird that the extra line-break seems to consistently end up at line ~530. I tried removing `messages` from the `importjs` output (I was getting a list of warnings here) to see if the line-break moved. It didn't, even though now the JSON result is shorter than before (and `messages` comes at the top).

**Comment by trotzig** [comment]
I've tried to reproduce the bug with this repro script, but the extra line-break doesn't appear as part of the output here:

``` py
import subprocess
import os

environment = dict(os.environ).copy()
environment.update({
    'LC_ALL': 'en_US.UTF-8',
    'LC_CTYPE': 'UTF-8',
    'LANG': 'en_US.UTF-8',
    'PATH': environment.get('PATH') + ':/usr/local/bin'
})
proc = subprocess.Popen(
    ['importjs', 'fix',
        'app/assets/components/pages/DistrictPage/index.jsx'],
    env=environment,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)
result = proc.communicate()
stdout = result[0].decode('utf-8')
stderr = result[1].decode('utf-8')

print(stdout)
```

**Comment by trotzig** [comment]
I found the issue. It was in import-js all along, but only appeared in the Sublime plugin because stdin data is passed in multiple chunks.
